import os
import json
from dotenv import load_dotenv
load_dotenv()
from difflib import SequenceMatcher
import re
from services.find_similar import find_similar_product
from services.generate_question import chain_to_find_categories_of_product,chain_to_obtain_columns,find_matching_products_model_and_brand,chain_to_obtain_columns_with_generating_sql_first

schema_file_location=r"C:\Users\prabigya\Desktop\work_here\Recommendo-Personalized-Shopping-Powered-by-LLMs\recommedation_algo_system\create_vector_database\database_schema.json"
with open(schema_file_location, 'r') as file:
    schema_data = json.load(file)

def categories_present_in_schema():
    return schema_data["categories_available"]

def return_schema_for_obtained_product_categories(json_data):
    schema={}
    for category in json_data["categories"]:
        schema[category]=schema_data["tables"][category]
    return schema

def get_related_products(user_query):
    api_key_1 = os.getenv('GEMINI_API_CODE2')
    model_used="gemini-1.5-flash-8b"
    category_finding_chain=chain_to_find_categories_of_product(api_key_1,model_used)
    # related_column_value_finder=chain_to_obtain_columns(api_key_1,model_used)
    related_column_finder_by_generating_sql_first=chain_to_obtain_columns_with_generating_sql_first(api_key_1,model_used)

    list_of_categories=categories_present_in_schema()
    # user_query="best iphone phones under 70220."

    query={
        "list_of_catrgories":list_of_categories,
        "user_query":user_query
    }

    categories_found= category_finding_chain.invoke(query)
    json_data= json.loads(str(categories_found["text"]).replace("```json","").replace("`","").strip())
    #print(json_data)
    schema_of_obtained_categories=return_schema_for_obtained_product_categories(json_data)

    table_schema=f""""{schema_of_obtained_categories}"""

    table_sample_rows="""apple,Apple iPhone 11 (128GB),308020,7.5,False,bionic,6.0,2.65,3110.0,False,,4,128,6.1,60,2,ios,12.0,12.0,False,1792,828
            oneplus,OnePlus 10 Pro 5G (12GB RAM + 256GB),429260,,True,snapdragon,8.0,3.0,5000.0,True,80.0,12,256,6.7,120,3,android,50.0,32.0,False,3216,1440"""

    query={"table_schema":table_schema,
        "user_query":user_query,
        "table_sample_input":table_sample_rows
    }
    query_for_sql={"table_schema":table_schema,
        "user_query":user_query}
    column_value_data=related_column_finder_by_generating_sql_first.invoke(query_for_sql)
    #print("column_value_data",column_value_data)
    column_value_data_json=json.loads(str(column_value_data["text"]).replace("```json","").replace("`","").strip())
    dict_of_columns_model_product=column_value_data_json.get("filters",{})
    #print(dict_of_columns_model_product)
    keys_checking_threshold={"brand_name":{"threshold":0.9,"value_avail":['apple', 'gionee', 'honor', 'huawei', 'oneplus', 'poco', 'realme',
        'redmi', 'samsung', 'vivo', 'xiaomi']},"model":{"threshold":0.75,"value_avail":['Apple iPhone 11', 'Apple iPhone 11 (128GB)',
        'Apple iPhone 11 Pro Max', 'Apple iPhone 12',
        'Apple iPhone 12 (128GB)', 'Apple iPhone 12 (256GB)',
        'Apple iPhone 12 Mini', 'Apple iPhone 12 Mini (128GB)',
        'Apple iPhone 12 Mini (256GB)', 'Apple iPhone 12 Pro (256GB)',
        'Apple iPhone 12 Pro (512GB)', 'Apple iPhone 13',
        'Apple iPhone 13 (256GB)', 'Apple iPhone 13 (512GB)',
        'Apple iPhone 13 Mini', 'Apple iPhone 13 Pro',
        'Apple iPhone 13 Pro (1TB)', 'Apple iPhone 13 Pro (256GB)',
        'Apple iPhone 13 Pro Max', 'Apple iPhone 13 Pro Max (1TB)',
        'Apple iPhone 13 Pro Max (256GB)', 'Apple iPhone 14',
        'Apple iPhone 14 (256GB)', 'Apple iPhone 14 (512GB)',
        'Apple iPhone 14 Mini', 'Apple iPhone 14 Plus',
        'Apple iPhone 14 Plus (256GB)', 'Apple iPhone 14 Plus (512GB)',
        'Apple iPhone 14 Pro', 'Apple iPhone 14 Pro (1TB)',
        'Apple iPhone 14 Pro (256GB)', 'Apple iPhone 14 Pro Max',
        'Apple iPhone 14 Pro Max (1TB)', 'Apple iPhone 14 Pro Max (256GB)',
        'Apple iPhone 14 Pro Max (512GB)', 'Apple iPhone 15',
        'Apple iPhone 15 Plus', 'Apple iPhone 15 Pro',
        'Apple iPhone 15 Pro Max', 'Apple iPhone 15 Ultra',
        'Apple iPhone 7s', 'Apple iPhone 9', 'Apple iPhone SE 2020',
        'Apple iPhone SE 3 2022', 'Apple iPhone SE 4', 'Apple iPhone XR2',
        'Gionee G13 Pro', 'Gionee K10', 'Gionee M12 Pro', 'Honor 50',
        'Honor 60 SE 5G', 'Honor 70 5G', 'Honor 70 5G (8GB RAM + 256GB)',
        'Honor 80 Pro Plus', 'Honor Magic 4 Pro Plus 5G', 'Honor Play 30',
        'Honor X6', 'Honor X7a', 'Honor X8', 'Honor X8 5G', 'Honor X9 5G',
        'Honor X9a', 'Huawei Honor 9N', 'Huawei Mate 30 RS Porsche Design',
        'Huawei Mate 40 Pro 4G', 'Huawei Mate 50 Pro 5G',
        'Huawei Mate 50 RS Porsche Design', 'Huawei Mate X',
        'Huawei Mate Xs 2', 'Huawei Nova 10', 'Huawei Nova 10 SE',
        'Huawei Nova 7i', 'Huawei Nova 9', 'Huawei Nova 9 SE',
        'Huawei Nova Y61', 'Huawei Nova Y90', 'Huawei P40 Pro',
        'Huawei P50 Pro 4G', 'OnePlus 10 Pro 5G',
        'OnePlus 10 Pro 5G (12GB RAM + 256GB)',
        'OnePlus 10 Pro 5G (12GB RAM + 512GB)', 'OnePlus 10R 5G',
        'OnePlus 10R 5G (12GB RAM + 256GB)', 'OnePlus 10R Prime Edition',
        'OnePlus 10T', 'OnePlus 10T (12GB RAM + 256GB)',
        'OnePlus 10T (16GB RAM + 256GB)', 'OnePlus 11 5G',
        'OnePlus 11 Pro', 'OnePlus 11R', 'OnePlus 12 Pro',
        'OnePlus 6 (8GB RAM + 128GB)', 'OnePlus 9 Pro', 'OnePlus 9RT 5G',
        'OnePlus 9T', 'OnePlus Ace 2', 'OnePlus Ace 5G', 'OnePlus Ace Pro',
        'OnePlus Ace Racing Edition 5G', 'OnePlus Clover',
        'OnePlus Nord 2 Lite 5G', 'OnePlus Nord 2T (12GB RAM + 256GB)',
        'OnePlus Nord 2T 5G', 'OnePlus Nord 3 5G', 'OnePlus Nord 3T 5G',
        'OnePlus Nord 4 5G', 'OnePlus Nord 5', 'OnePlus Nord CE 2 Lite 5G',
        'OnePlus Nord CE 2 Lite 5G (8GB RAM + 128GB)',
        'OnePlus Nord CE 2 Lite 5G (8GB RAM + 256GB)',
        'OnePlus Nord CE 3 5G', 'OnePlus Nord CE 3 Lite 5G',
        'OnePlus Nord Lite', 'OnePlus Nord N10', 'OnePlus Nord N100',
        'OnePlus Nord N20 5G', 'OnePlus Nord N200', 'OnePlus Nord N300',
        'OnePlus Nord SE', 'OnePlus Z', 'POCO C31',
        'POCO C31 (4GB RAM + 64GB)', 'Poco C50',
        'Poco C50 (3GB RAM + 32GB)', 'Poco C55', 'Poco F3 GT',
        'Poco F4 (12GB RAM + 256GB)', 'Poco F4 5G',
        'Poco F4 5G (8GB RAM + 128GB)', 'POCO F4 GT 5G', 'Poco F5',
        'POCO F5 GT 5G', 'Poco F5 Pro', 'Poco M2', 'POCO M2 Pro',
        'Poco M3', 'POCO M3 Pro 5G', 'POCO M3 Pro 5G (6GB RAM + 128GB)',
        'Poco M4 5G', 'Poco M4 5G (6GB RAM + 128GB)', 'POCO M4 Pro 4G',
        'POCO M4 Pro 4G (6GB RAM + 128GB)',
        'POCO M4 Pro 4G (8GB RAM + 128GB)', 'Poco M4 Pro 5G',
        'Poco M4 Pro 5G (6GB RAM + 128GB)',
        'Poco M4 Pro 5G (8GB RAM + 128GB)', 'Poco M5',
        'Poco M5 (6GB RAM + 128GB)', 'Poco M6 Pro', 'Poco X3',
        'Poco X3 Pro', 'Poco X4', 'POCO X4 GT 5G',
        'POCO X4 GT 5G (8GB RAM + 256GB)', 'Poco X4 Pro 5G',
        'Poco X4 Pro 5G (6GB RAM + 128GB)',
        'Poco X4 Pro 5G (8GB RAM + 128GB)', 'Poco X5', 'POCO X5 GT',
        'Poco X5 Pro', 'Poco X6 Pro 5G', 'Realme 10',
        'Realme 10 (8GB RAM + 128GB)', 'Realme 10 5G', 'Realme 10 Pro',
        'Realme 10 Pro (8GB RAM + 128GB)', 'Realme 10 Pro Plus',
        'Realme 10 Pro Plus (8GB RAM + 256GB)', 'Realme 10s',
        'Realme 11 Pro', 'Realme 11 Pro Plus', 'Realme 6 (6GB RAM + 64GB)',
        'Realme 6 Pro', 'Realme 7 Pro (8GB RAM + 128GB)', 'Realme 8',
        'Realme 8 (8GB RAM + 128GB)', 'Realme 8 5G',
        'Realme 8 5G (8GB RAM + 128GB)', 'Realme 8i',
        'Realme 8i (6GB RAM + 128GB)', 'Realme 8s 5G',
        'Realme 8s 5G (8GB RAM + 128GB)', 'Realme 9 4G',
        'Realme 9 4G (8GB RAM + 128GB)', 'Realme 9 5G',
        'Realme 9 5G (6GB RAM + 128GB)', 'Realme 9 5G SE',
        'Realme 9 5G SE (8GB RAM + 128GB)', 'Realme 9 Pro 5G',
        'Realme 9 Pro 5G (8GB RAM + 128GB)', 'Realme 9 Pro Plus 5G',
        'Realme 9 Pro Plus 5G (8GB RAM + 128GB)',
        'Realme 9 Pro Plus 5G (8GB RAM + 256GB)', 'Realme 9i',
        'Realme 9i (4GB RAM + 128GB)', 'Realme 9i (6GB RAM + 128GB)',
        'Realme 9i 5G', 'Realme 9i 5G (6GB RAM + 128GB)', 'Realme A1',
        'Realme C11', 'Realme C11 2021',
        'Realme C11 2021 (4GB RAM + 64GB)', 'Realme C2', 'Realme C21Y',
        'Realme C25Y (4GB RAM + 64GB)', 'Realme C2s', 'Realme C30',
        'Realme C30 (3GB RAM + 32GB)', 'Realme C30s',
        'Realme C30s (4GB RAM + 64GB)', 'Realme C31',
        'Realme C31 (4GB RAM + 64GB)', 'Realme C32', 'Realme C33',
        'Realme C33 (4GB RAM + 64GB)', 'Realme C35',
        'Realme C35 (4GB RAM + 128GB)', 'Realme C35 (6GB RAM + 128GB)',
        'Realme G1', 'Realme GT 2 5G',
        'Realme GT 2 Explorer Master Edition', 'Realme GT 2 Pro 5G',
        'Realme GT 2 Pro 5G (12GB RAM + 256GB)', 'Realme GT 5G',
        'Realme GT Explorer Master Edition', 'Realme GT Master Edition 5G',
        'Realme GT Neo 3 5G', 'Realme GT Neo 3T',
        'Realme GT Neo 3T (8GB RAM + 128GB)',
        'Realme GT Neo 3T (8GB RAM + 256GB)', 'Realme GT Neo 4T',
        'Realme GT Neo 5', 'Realme GT Neo2 5G', 'Realme Narzo 20',
        'Realme Narzo 30 5G', 'Realme Narzo 30 Pro 5G (8GB RAM +128GB)',
        'Realme Narzo 50', 'Realme Narzo 50 (6GB RAM + 128GB)',
        'Realme Narzo 50 5G', 'Realme Narzo 50 5G (4GB RAM + 128GB)',
        'Realme Narzo 50 5G (4GB RAM + 64GB)', 'Realme Narzo 50 Pro 5G',
        'Realme Narzo 50 Pro 5G (8GB RAM + 128GB)', 'Realme Narzo 50A',
        'Realme Narzo 50A Prime',
        'Realme Narzo 50A Prime (4GB RAM + 128GB)', 'Realme Narzo 50i',
        'Realme Narzo 50i (4GB RAM + 64GB)', 'Realme Narzo 50i Prime',
        'Realme Narzo 50i Prime (4GB RAM + 64GB)', 'Realme Q2i',
        'Realme Q3', 'Realme Q3i 5G', 'Realme Q5 5G',
        'Realme X50 Pro 5G (12GB RAM + 256GB)',
        'Realme X50 Pro 5G (8GB RAM + 128GB)', 'Realme X7 Max',
        'Realme XT', 'Redmi 12C', 'Redmi Note 11 Pro 2023',
        'Redmi Note 12 Pro Speed Edition', 'Samsung Galaxy A01 Core',
        'Samsung Galaxy A03', 'Samsung Galaxy A03 (4GB RAM + 64GB)',
        'Samsung Galaxy A03 Core', 'Samsung Galaxy A03s',
        'Samsung Galaxy A04', 'Samsung Galaxy A04 (4GB RAM + 128GB)',
        'Samsung Galaxy A04e', 'Samsung Galaxy A04e (3GB RAM + 64GB)',
        'Samsung Galaxy A04e (4GB RAM + 128GB)', 'Samsung Galaxy A04s',
        'Samsung Galaxy A04s (4GB RAM + 128GB)', 'Samsung Galaxy A05',
        'Samsung Galaxy A11', 'Samsung Galaxy A12',
        'Samsung Galaxy A12 (6GB RAM + 128GB)', 'Samsung Galaxy A13',
        'Samsung Galaxy A13 (4GB RAM + 128GB)',
        'Samsung Galaxy A13 (6GB RAM + 128GB)', 'Samsung Galaxy A13 5G',
        'Samsung Galaxy A14 5G', 'Samsung Galaxy A14 5G (6GB RAM + 128GB)',
        'Samsung Galaxy A14 5G (8GB RAM + 128GB)', 'Samsung Galaxy A15',
        'Samsung Galaxy A21s (6GB RAM + 128GB)', 'Samsung Galaxy A22',
        'Samsung Galaxy A22 5G', 'Samsung Galaxy A23',
        'Samsung Galaxy A23 (8GB RAM + 128GB)', 'Samsung Galaxy A23 5G',
        'Samsung Galaxy A23 5G (8GB RAM + 128GB)', 'Samsung Galaxy A24',
        'Samsung Galaxy A32', 'Samsung Galaxy A32 (8GB RAM + 128GB)',
        'Samsung Galaxy A32 5G', 'Samsung Galaxy A33 5G',
        'Samsung Galaxy A33 5G (8GB RAM + 128GB)', 'Samsung Galaxy A34 5G',
        'Samsung Galaxy A40', 'Samsung Galaxy A50s', 'Samsung Galaxy A52',
        'Samsung Galaxy A52 (8GB RAM + 128GB)',
        'Samsung Galaxy A53 (8GB RAM + 256GB)', 'Samsung Galaxy A53 5G',
        'Samsung Galaxy A53 5G (8GB RAM + 128GB)', 'Samsung Galaxy A54 5G',
        'Samsung Galaxy A7 (2018)', 'Samsung Galaxy A71',
        'Samsung Galaxy A73 5G', 'Samsung Galaxy A73 5G (8GB RAM + 256GB)',
        'Samsung Galaxy A74 5G', 'Samsung Galaxy A75 5G',
        'Samsung Galaxy A82 5G', 'Samsung Galaxy A83 5G',
        'Samsung Galaxy A9 Pro (2019)', 'Samsung Galaxy A92 5G',
        'Samsung Galaxy F04', 'Samsung Galaxy F12', 'Samsung Galaxy F13',
        'Samsung Galaxy F13 (4GB RAM + 128GB)', 'Samsung Galaxy F14',
        'Samsung Galaxy F22', 'Samsung Galaxy F22 (6GB RAM + 128GB)',
        'Samsung Galaxy F23 5G', 'Samsung Galaxy F23 5G (6GB RAM + 128GB)',
        'Samsung Galaxy F24 5G', 'Samsung Galaxy F41 (6GB RAM + 128GB)',
        'Samsung Galaxy F42 5G', 'Samsung Galaxy F42 5G (8GB RAM + 128GB)',
        'Samsung Galaxy F63', 'Samsung Galaxy M04',
        'Samsung Galaxy M04 (4GB RAM + 128GB)', 'Samsung Galaxy M12',
        'Samsung Galaxy M13', 'Samsung Galaxy M13 (4GB RAM + 64GB)',
        'Samsung Galaxy M13 5G', 'Samsung Galaxy M13 5G (4GB RAM + 64GB)',
        'Samsung Galaxy M14', 'Samsung Galaxy M21 2021',
        'Samsung Galaxy M32', 'Samsung Galaxy M32 (6GB RAM + 128GB)',
        'Samsung Galaxy M32 Prime Edition',
        'Samsung Galaxy M32 Prime Edition (6GB RAM + 128GB)',
        'Samsung Galaxy M33 5G', 'Samsung Galaxy M33 5G (8GB RAM + 128GB)',
        'Samsung Galaxy M34 5G', 'Samsung Galaxy M35',
        'Samsung Galaxy M51s 5G', 'Samsung Galaxy M52s 5G',
        'Samsung Galaxy M53 5G', 'Samsung Galaxy M53 5G (8GB RAM + 128GB)',
        'Samsung Galaxy M54 5G', 'Samsung Galaxy M62',
        'Samsung Galaxy Note 10 Lite', 'Samsung Galaxy Note 10 Plus',
        'Samsung Galaxy Note 10 Plus 5G', 'Samsung Galaxy Note 20',
        'Samsung Galaxy Note 30 Ultra 5G', 'Samsung Galaxy S10 5G',
        'Samsung Galaxy S10 Plus', 'Samsung Galaxy S20',
        'Samsung Galaxy S20 5G', 'Samsung Galaxy S20 FE',
        'Samsung Galaxy S20 FE 5G', 'Samsung Galaxy S20 Plus',
        'Samsung Galaxy S20 Plus 5G', 'Samsung Galaxy S20 Ultra 5G',
        'Samsung Galaxy S21', 'Samsung Galaxy S21 FE 5G',
        'Samsung Galaxy S21 FE 5G (8GB RAM + 256GB)',
        'Samsung Galaxy S21 Plus', 'Samsung Galaxy S21 Ultra',
        'Samsung Galaxy S21 Ultra 5G (12GB RAM + 128GB)',
        'Samsung Galaxy S22 5G', 'Samsung Galaxy S22 5G (8GB RAM + 256GB)',
        'Samsung Galaxy S22 FE 5G', 'Samsung Galaxy S22 Plus 5G',
        'Samsung Galaxy S22 Plus 5G (8GB RAM + 256GB)',
        'Samsung Galaxy S22 Ultra 5G',
        'Samsung Galaxy S22 Ultra 5G (12GB RAM + 512GB)',
        'Samsung Galaxy S22 Ultra 5G (8GB RAM + 128GB)',
        'Samsung Galaxy S23', 'Samsung Galaxy S23 FE 5G',
        'Samsung Galaxy S23 Plus', 'Samsung Galaxy S23 Ultra 5G',
        'Samsung Galaxy S24 Ultra', 'Samsung Galaxy S9 Plus (128GB)',
        'Samsung Galaxy Z Flip 3', 'Samsung Galaxy Z Flip 4 5G',
        'Samsung Galaxy Z Fold 3', 'Samsung Galaxy Z Fold 4',
        'Samsung Galaxy Z Fold 4 (12GB RAM + 1TB)', 'Vivo S1 Pro',
        'Vivo S16', 'Vivo S16 Pro', 'Vivo S17 Pro', 'Vivo T1 44W',
        'Vivo T1 44W (6GB RAM + 128GB)', 'Vivo T1 44W (8GB RAM + 128GB)',
        'Vivo T1 5G', 'Vivo T1 5G (6GB RAM + 128GB)',
        'Vivo T1 5G (8GB RAM + 128GB)', 'Vivo T1 Pro',
        'Vivo T1 Pro 5G (8GB RAM + 128GB)', 'Vivo T1x (4GB RAM + 128GB)',
        'Vivo T1x (6GB RAM + 128GB)', 'Vivo T1x 4G', 'Vivo T2 5G',
        'Vivo T2 Pro 5G', 'Vivo T2x 5G', 'Vivo T3 Pro', 'Vivo U3',
        'Vivo U3 (6GB RAM + 64GB)', 'Vivo U3x', 'Vivo V11i',
        'Vivo V15 Pro (8GB RAM +128GB)', 'Vivo V19 (8GB RAM + 256GB)',
        'Vivo V20', 'Vivo V20 Pro', 'Vivo V20 SE', 'Vivo V21',
        'Vivo V21 5G', 'Vivo V21 Pro', 'Vivo V21s', 'Vivo V23 5G',
        'Vivo V23 5G (12GB RAM + 256GB)', 'Vivo V23 Pro 5G',
        'Vivo V23 Pro 5G (12GB RAM + 256GB)', 'Vivo V23e', 'Vivo V23e 5G',
        'Vivo V25 (12GB RAM + 256GB)', 'Vivo V25 5G',
        'Vivo V25 Pro (12GB RAM + 256GB)', 'Vivo V25 Pro 5G', 'Vivo V25e',
        'Vivo V26 Pro', 'Vivo V27', 'Vivo V27 Pro', 'Vivo V28', 'Vivo V29',
        'Vivo X Fold 2', 'Vivo X Fold 5G',
        'Vivo X Fold 5G (12GB RAM + 512GB)', 'Vivo X Fold Plus',
        'Vivo X Note 5G (12GB RAM + 512GB)', 'Vivo X80 5G',
        'Vivo X80 5G (12GB RAM + 256GB)', 'Vivo X80 Pro 5G',
        'Vivo X80 Pro Plus 5G', 'Vivo X90 5G', 'Vivo X90 Pro 5G',
        'Vivo X90 Pro Plus 5G', 'Vivo Y01', 'Vivo Y01A', 'Vivo Y02',
        'Vivo Y02 (2GB RAM + 32GB)', 'Vivo Y02s', 'Vivo Y10', 'Vivo Y100',
        'Vivo Y11 (2019)', 'Vivo Y12 (3GB RAM + 64GB)', 'Vivo Y12a',
        'Vivo Y12G (3GB RAM + 64GB)', 'Vivo Y15', 'Vivo Y15C',
        'Vivo Y15C (3GB RAM + 64GB)', 'Vivo Y15s', 'Vivo Y16',
        'Vivo Y16 (3GB RAM + 64GB)', 'Vivo Y16 (4GB RAM + 64GB)',
        'Vivo Y19', 'Vivo Y20G', 'Vivo Y21 (2020)', 'Vivo Y21 2021',
        'Vivo Y21e', 'Vivo Y21s', 'Vivo Y21T', 'Vivo Y22',
        'Vivo Y22 (6GB RAM + 128GB)', 'Vivo Y22s', 'Vivo Y25',
        'Vivo Y3 (4GB RAM + 128GB)', 'Vivo Y33s', 'Vivo Y33T', 'Vivo Y35',
        'Vivo Y35 5G', 'Vivo Y53s', 'Vivo Y53t', 'Vivo Y55 4G',
        'Vivo Y55 5G', 'Vivo Y55S', 'Vivo Y55s 2023', 'Vivo Y55s 5G',
        'Vivo Y71', 'Vivo Y73 2021', 'Vivo Y73T', 'Vivo Y75 4G',
        'Vivo Y75 5G', 'Vivo Y77 5G', 'Vivo Y78 5G', 'Vivo Y91c',
        'Vivo Y93', 'Vivo Y95', 'Xiaomi 11i 5G (8GB RAM + 128GB)',
        'Xiaomi 11i HyperCharge 5G',
        'Xiaomi 11i HyperCharge 5G (8GB RAM + 128GB)',
        'Xiaomi 11T Pro 5G (12GB RAM + 256GB)', 'Xiaomi 12 Lite 5G',
        'Xiaomi 12 Pro 5G', 'Xiaomi 12 Pro 5G (12GB RAM + 256GB)',
        'Xiaomi 12 Ultra 5G', 'Xiaomi 12S Ultra', 'Xiaomi 12T',
        'Xiaomi 12T Pro 5G', 'Xiaomi 13 5G', 'Xiaomi 13 Pro 5G',
        'Xiaomi 13 Ultra 5G', 'Xiaomi 14', 'Xiaomi Civi 2',
        'Xiaomi Civi 3', 'Xiaomi Mi 10 5G (8GB RAM + 256GB)',
        'Xiaomi Mi 10T 5G', 'Xiaomi Mi 10T Pro 5G',
        'Xiaomi Mi 11 Lite (8GB RAM + 128GB)', 'Xiaomi Mi 11 Lite NE 5G',
        'Xiaomi Mi 11 Lite NE 5G (8GB RAM + 128GB)', 'Xiaomi Mi 11i 5G',
        'Xiaomi Mi 11T Pro 5G', 'Xiaomi Mi 11X',
        'Xiaomi Mi 11X 5G (8GB RAM + 128GB)', 'Xiaomi Mi 11X Pro',
        'Xiaomi Mi 12 5G', 'Xiaomi Mi Mix Alpha', 'Xiaomi Mi Mix Fold',
        'Xiaomi Mix Fold 2 5G', 'Xiaomi Poco F1',
        'Xiaomi Poco F1 (6GB RAM + 128GB)', 'Xiaomi Redmi 10',
        'Xiaomi Redmi 10 (6GB RAM + 128GB)', 'Xiaomi Redmi 10 Power',
        'Xiaomi Redmi 10 Prime', 'Xiaomi Redmi 10 Prime (6GB RAM + 128GB)',
        'Xiaomi Redmi 10 Prime Plus 5G', 'Xiaomi Redmi 10A',
        'Xiaomi Redmi 10A (4GB RAM + 64GB)',
        'Xiaomi Redmi 10A (6GB RAM + 128GB)', 'Xiaomi Redmi 10A Sport',
        'Xiaomi Redmi 10C', 'Xiaomi Redmi 10C (4GB RAM + 128GB)',
        'Xiaomi Redmi 11 Prime', 'Xiaomi Redmi 11 Prime (6GB RAM + 128GB)',
        'Xiaomi Redmi 11 Prime 5G',
        'Xiaomi Redmi 11 Prime 5G (6GB RAM + 128GB)',
        'Xiaomi Redmi 13 Prime 5G', 'Xiaomi Redmi 20X',
        'Xiaomi Redmi 8 (4GB RAM + 64GB)', 'Xiaomi Redmi 9',
        'Xiaomi Redmi 9 Activ', 'Xiaomi Redmi 9 Activ (6GB RAM + 128GB)',
        'Xiaomi Redmi 9 Power', 'Xiaomi Redmi 9A',
        'Xiaomi Redmi 9A (6GB RAM + 128GB)', 'Xiaomi Redmi 9A Sport',
        'Xiaomi Redmi 9i (4GB RAM + 128GB)', 'Xiaomi Redmi 9i Sport',
        'Xiaomi Redmi A1', 'Xiaomi Redmi A1 Plus',
        'Xiaomi Redmi A1 Plus (3GB RAM + 32GB)',
        'Xiaomi Redmi K20 Pro Signature Edition', 'Xiaomi Redmi K50 5G',
        'Xiaomi Redmi K50 Ultra 5G', 'Xiaomi Redmi K50i (8GB RAM + 256GB)',
        'Xiaomi Redmi K50i 5G', 'Xiaomi Redmi K60',
        'Xiaomi Redmi K60 Gaming Edition', 'Xiaomi Redmi K60 Pro',
        'Xiaomi Redmi K60E', 'Xiaomi Redmi K60i', 'Xiaomi Redmi Note 10',
        'Xiaomi Redmi Note 10 (6GB RAM + 128GB)',
        'Xiaomi Redmi Note 10 5G', 'Xiaomi Redmi Note 10 Lite',
        'Xiaomi Redmi Note 10 Lite (4GB RAM + 128GB)',
        'Xiaomi Redmi Note 10 Lite (6GB RAM + 128GB)',
        'Xiaomi Redmi Note 10 Pro (6GB RAM + 128GB)',
        'Xiaomi Redmi Note 10 Pro 5G', 'Xiaomi Redmi Note 10 Pro Max',
        'Xiaomi Redmi Note 10 Pro Max (6GB RAM + 128GB)',
        'Xiaomi Redmi Note 10S', 'Xiaomi Redmi Note 10S (6GB RAM + 128GB)',
        'Xiaomi Redmi Note 10S (8GB RAM + 128GB)',
        'Xiaomi Redmi Note 10T 5G',
        'Xiaomi Redmi Note 10T 5G (6GB RAM +128GB)',
        'Xiaomi Redmi Note 11', 'Xiaomi Redmi Note 11 (6GB RAM + 128GB)',
        'Xiaomi Redmi Note 11 (6GB RAM + 64GB)', 'Xiaomi Redmi Note 11 5G',
        'Xiaomi Redmi Note 11 Pro 4G', 'Xiaomi Redmi Note 11 Pro 5G',
        'Xiaomi Redmi Note 11 Pro Max 5G',
        'Xiaomi Redmi Note 11 Pro Plus 5G',
        'Xiaomi Redmi Note 11 Pro Plus 5G (8GB RAM + 128GB)',
        'Xiaomi Redmi Note 11 Pro Plus 5G (8GB RAM + 256GB)',
        'Xiaomi Redmi Note 11E 5G', 'Xiaomi Redmi Note 11R',
        'Xiaomi Redmi Note 11S', 'Xiaomi Redmi Note 11S (6GB RAM + 128GB)',
        'Xiaomi Redmi Note 11S (8GB RAM + 128GB)',
        'Xiaomi Redmi Note 11SE', 'Xiaomi Redmi Note 11T 5G',
        'Xiaomi Redmi Note 11T 5G (6GB RAM + 128GB)',
        'Xiaomi Redmi Note 11T 5G (8GB RAM + 128GB)',
        'Xiaomi Redmi Note 11T Pro 5G', 'Xiaomi Redmi Note 12',
        'Xiaomi Redmi Note 12 (6GB RAM + 128GB)',
        'Xiaomi Redmi Note 12 4G',
        'Xiaomi Redmi Note 12 Discovery Edition',
        'Xiaomi Redmi Note 12 Explorer',
        'Xiaomi Redmi Note 12 Pro (8GB RAM + 128GB)',
        'Xiaomi Redmi Note 12 Pro (8GB RAM + 256GB)',
        'Xiaomi Redmi Note 12 Pro 4G', 'Xiaomi Redmi Note 12 Pro 5G',
        'Xiaomi Redmi Note 12 Pro Max 5G', 'Xiaomi Redmi Note 12 Pro Plus',
        'Xiaomi Redmi Note 12 Pro Plus (12GB RAM + 256GB)',
        'Xiaomi Redmi Note 12 Pro Plus (6GB RAM + 128GB)',
        'Xiaomi Redmi Note 12 Turbo', 'Xiaomi Redmi Note 12T 5G',
        'Xiaomi Redmi Note 13 Pro 5G', 'Xiaomi Redmi Note 13 Pro Max 5G',
        'Xiaomi Redmi Note 4', 'Xiaomi Redmi Note 8 2021',
        'Xiaomi Redmi Note 8 Pro', 'Xiaomi Redmi Note 9',
        'Xiaomi Redmi Note 9 Pro',
        'Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB)',
        'Xiaomi Redmi Note 9 Pro Max']}}
    keys_to_check=list(keys_checking_threshold.keys())
    keys_present_in_obtained_col_prod_dict=list(dict_of_columns_model_product.keys())
    #print("heeeereeee")
    for key in keys_to_check:
        if key in keys_present_in_obtained_col_prod_dict:
            #print(dict_of_columns_model_product[key],keys_checking_threshold[key]["threshold"])
            obtained_data=find_matching_products_model_and_brand(dict_of_columns_model_product[key]["value"],keys_checking_threshold[key]["value_avail"],threshold=keys_checking_threshold[key]["threshold"])
            #print(obtained_data)
            if len(obtained_data)==0:
                dict_of_columns_model_product[key]["value"]=obtained_data
                try:
                    del dict_of_columns_model_product[key]
                except:
                    pass
            else:  
                dict_of_columns_model_product[key]["value"]=obtained_data
    #print(dict_of_columns_model_product)
    return dict_of_columns_model_product
    # return find_similar_product(dict_of_model_brand=dict_of_columns_model_product)
